on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build_4_3_0:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Haxe 4.3.0
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Haxe Version
        run: haxe -version

      - name: Run Test
        working-directory: test
        run: haxe Test.hxml

  build_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Haxe Latest
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: latest

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Haxe Version
        run: haxe -version

      - name: Run Test
        working-directory: test
        run: haxe Test.hxml